In [1]:
import numpy as np


In [4]:
# 1.Create a 1D NumPy array of the first 10 even numbers.
n=np.arange(0,10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 2.Create a 3x3 array of all zeros, then a 3x3 identity matrix.
n=np.zeros(9).reshape(3,3)
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# 3.Create np.arange(20), reshape it into a 4x5 array, and print its .ndim, .shape, and .size.
n=np.arange(20).reshape(4,5)
print(n.ndim)
print(n.shape)
print(n.size)

2
(4, 5)
20


In [13]:
# 4.Create an array with mixed values [1, 2.5, 3] and print its dtype.
n=np.array([1,2.5,3])
print(n.dtype)

float64


In [14]:
# 5.Create a 1D array of 8 elements using np.linspace(0, 100, 8).
n=np.linspace(0,100,8)
print(n)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [15]:
# 6.Generate 5 random integers between 50 and 100 using np.random.randint().
n=np.random.randint(50,101,5)
print(n)

[61 69 91 54 59]


In [17]:
# 7.Create a (2,3) array of ones and check its .itemsize and total memory (itemsize * size).
n=np.ones(6).reshape(2,3)
print(n.itemsize)
print(n.itemsize * n.size)

8
48


In [21]:
# 8. Given arr = np.arange(1, 21).reshape(4,5), extract the 2nd and 3rd rows using slicing.
n=np.arange(1, 21).reshape(4,5)
# print(n)
print(n[2:4,:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
# 9. From a marks array [55, 67, 89, 32, 90, 41, 76], use boolean indexing to get marks that are ≥ 40 and < 85.
n=np.array([55, 67, 89, 32, 90, 41, 76])
print(n[(n>=40) & (n<85)])

[55 67 41 76]


In [38]:
# 10. Use fancy indexing to select the elements at indices [1, 3, 5] from np.arange(10, 20).
n=np.arange(10, 20)
print(n[[1,3,5]])

[11 13 15]


In [48]:
# 11. Create a (3,1) array and a (1,4) array, add them together using broadcasting, and print the result's shape.
n=np.array([1,2,3]).reshape(3,1)
m=np.array([5,6,7,8]).reshape(1,4)
print(n+m)

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]


In [53]:
# 12. Given a (4,4) array of np.arange(16).reshape(4,4), print its transpose.
n=np.arange(16).reshape(4,4)
print(n.T) #or n.transpose()

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [66]:
# 13. Create a (2,3) array and produce both its .flatten() and .ravel() versions, then modify the raveled version's first element and print the original array.
n=np.arange(0,6).reshape(2,3)
print(n)
print(n.flatten())
rav=n.ravel()
rav[0]=45678
print(rav)
print(n)


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[45678     1     2     3     4     5]
[[45678     1     2]
 [    3     4     5]]


In [70]:
# 14. Given arr = np.arange(1, 13), reshape it to (3,4) and then use .reshape(-1) to flatten it back to 1D.
n=np.arange(1, 13).reshape(3,4)
print(n)
print(n.reshape(-1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [1]:
# 15. Iterate through a (2,3) 2D array using np.nditer()
n=np.arange(6).reshape(2,3)
print(n)
for i in np.nditer(n):
    print(i)

NameError: name 'np' is not defined

In [ ]:
# Q1. Replace all odd numbers in the given array with -1
#  input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#  expected Output->[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

# Q2. Convert a 1-D array into a 2-D array with 3 rows
# input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) output = [[ 0, 1, 2],[3, 4, 5],[6, 7, 8]]

# Q3. Create a 2-D array with 202 to all the values
# Output = [[202, 202],[202, 202]]

# Q4. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
# output = [36, 30, 36, 38, 31, 35, 36, 30, 32, 34]

# Q.6 Create a null vector of size 10
# output = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Q.7 Create a null vector of size 10 but the fifth value which is 1
# output = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

# Q.8 Reverse a vector (first element becomes last)

# Q.9 Create a 3x3 identity matrix

# Q.11 Create a 10x10 array with random values and find the minimum and maximum values

# Q.16 How to convert a float (32 bits) array into an integer (32 bits) in place?

# Q.13 Create a 2d array with 1 on the border and 0 inside

In [12]:
# Q1. Replace all odd numbers in the given array with -1
#  input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#  expected Output->[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where((input%2==0),-1,input))

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [14]:
# Q2. Convert a 1-D array into a 2-D array with 3 rows
# input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) output = [[ 0, 1, 2],[3, 4, 5],[6, 7, 8]]

input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(input.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# Q3. Create a 2-D array with 202 to all the values
# Output = [[202, 202],[202, 202]]

print(np.full((2,2),202))

[[202 202]
 [202 202]]


In [21]:
# Q4. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
# output = [36, 30, 36, 38, 31, 35, 36, 30, 32, 34]

arr=np.random.randint(30,41,10)
print(arr)

[30 40 31 32 37 32 37 37 34 39]


In [56]:
# Q.6 Create a null vector of size 10
# output = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
# Q.7 Create a null vector of size 10 but the fifth value which is 1
# output = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

arr=np.full((10,),0)
print(arr)
arr[4]=1
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [32]:
# Q.8 Reverse a vector (first element becomes last)

print(input[::-1])

[8 7 6 5 4 3 2 1 0]


In [37]:
# Q.9 Create a 3x3 identity matrix

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Q.11 Create a 10x10 array with random values and find the minimum and maximum values

arr=np.random.randint(0,1001,100).reshape(10,-1)
print(arr)
max=arr[[0:0,0:0]]
min=arr[[0:0,0:0]]

# min=0
for i in np.nditer(arr):
    if i>max:
        max=i
    elif i<min:
        min=i
print(max)
print(min)

[[772 787 343 674 358 288 489 615 666 947]
 [349 885 676 901 612 860 507 106 520 196]
 [396 853 920 345 402 286 359  43  10 941]
 [536 265 988 953 325 317 228 782 419 114]
 [111 608 235 341 245 558 389 230 285 285]
 [843 385 381 892 857 230 400 674  89 846]
 [123 618 539 479 249 876 134 543 774 963]
 [ 68 154 207 557 493 642 660 114  20 868]
 [409 335 157 194 641 376  19  15 684 267]
 [688 642 590 902 438 320 694 375  67 469]]
988
0


In [67]:
# Q.16 How to convert a float (32 bits) array into an integer (32 bits) in place?

ss=np.zeros(2)
print(ss)
ss.dtype=int
print(ss)

[0. 0.]
[0 0]


In [72]:
# Q.13 Create a 2d array with 1 on the border and 0 inside

on=np.ones(16).reshape(4,4)
print(on)
on[1:3,1:3]=0
print(on)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [2]:
# 1. Create a 1D array of numbers from 50 to 100 with a step of 5.
# 2. Given arr = np.array([[4,8],[15,16]]), print its .dtype and convert it to float32.
# 3. Create a (3,3) array of random integers between 1-9 and print its transpose.
# 4. Given arr = np.arange(30).reshape(5,6), extract the last 2 columns using slicing.
# 5. Use boolean indexing on np.array([12,45,7,89,23,56]) to get all values divisible by 3.
# 6. Given A = np.array([[2,1],[1,3]]) and B = np.array([[1,0],[0,1]]), compute A @ B.
# 7. Set np.random.seed(15) and generate a (3,3) array of random integers 1-20.
# 8. Given marks = np.array([56,78,92,34,88,67,45]), compute mean, median, and standard
# deviation.
# 9. Given a (4,5) array of random integers, find the sum of each row and each column separately
# using axis.
# 10. Create a (2,4) array and use .flatten() and .ravel() — modify each result and observe which
# one changes the original array.
# 11. Given temps = np.array([98.6, 101.2, 97.4, 103.5, 99.1]), label each as "Fever" if above 100,
# else "Normal".
# 12. Given arr = np.array([5,12,8,25,3,19]), find the 2nd smallest value without using a loop.
# 14. Given a = np.array([1,2,3]) and b = np.array([[1],[2],[3]]), predict and verify the shape of a *
# b.
# 15. Create an array of 15 random integers between 1-100, then use np.unique() 
# 16. Given prices = np.array([199,450,89,999,320]), use np.clip() to cap all prices between 100
# and 500.

In [4]:
# 1. Create a 1D array of numbers from 50 to 100 with a step of 5.
n=np.arange(50,101,5)
print(n)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [10]:
# 2. Given arr = np.array([[4,8],[15,16]]), print its .dtype and convert it to float32.
arr = np.array([[4,8],[15,16]])
print(arr.dtype)
arr.dtype=float
print(arr.dtype)

int64
float64


In [21]:
# 3. Create a (3,3) array of random integers between 1-9 and print its transpose.
a=np.random.randint(1,10,9).reshape(3,3)
print(a)
print(a.T)

[[3 7 6]
 [8 1 7]
 [9 8 4]]
[[3 8 9]
 [7 1 8]
 [6 7 4]]


In [27]:
# 4. Given arr = np.arange(30).reshape(5,6), extract the last 2 columns using slicing.
arr = np.arange(30).reshape(5,6)

print(arr)
print(arr[:,4:])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


In [31]:
# 5. Use boolean indexing on np.array([12,45,7,89,23,56]) to get all values divisible by 3.
a=np.array([12,45,7,89,23,56])
print(a[a%2==0])

[12 56]


In [36]:
# 6. Given A = np.array([[2,1],[1,3]]) and B = np.array([[1,0],[0,1]]), compute A @ B.
A = np.array([[2,1],[1,3]])
B = np.array([[1,0],[0,1]])
print(A@B)

[[2 1]
 [1 3]]


In [46]:
# 10. Create a (2,4) array and use .flatten() and .ravel() — modify each result and observe which
# one changes the original array.
a=np.arange(8).reshape(2,4)
print(a)
fla=a.flatten()
fla[0]=67823
print(fla)
print(a)
rav=a.ravel()
rav[0]=67823
print(fla)
print(a)

[[0 1 2 3]
 [4 5 6 7]]
[67823     1     2     3     4     5     6     7]
[[0 1 2 3]
 [4 5 6 7]]
[67823     1     2     3     4     5     6     7]
[[67823     1     2     3]
 [    4     5     6     7]]


In [50]:
# 11. Given temps = np.array([98.6, 101.2, 97.4, 103.5, 99.1]), label each as "Fever" if above 100,
# else "Normal".
temps = np.array([98.6, 101.2, 97.4, 103.5, 99.1])
print(np.where(temps>100,"fever","normal"))

['normal' 'fever' 'normal' 'fever' 'normal']


In [69]:
# 12. Given arr = np.array([5,12,8,25,3,19]), find the 2nd smallest value without using a loop.
arr = np.array([5,12,8,25,3,19])
print(arr)
sorted=np.sort(arr)
print(np.sort(arr))
print(sorted[1])

[ 5 12  8 25  3 19]
[ 3  5  8 12 19 25]
5


In [59]:
# 14. Given a = np.array([1,2,3]) and b = np.array([[1],[2],[3]]), predict and verify the shape of a * b.
a = np.array([1,2,3]) 
b = np.array([[1],[2],[3]])
c=a*b
print(c.shape)

(3, 3)


In [64]:
# 15. Create an array of 15 random integers between 1-100, then use np.unique() 
n=np.random.randint(1,101,15)
print(n)
print(np.unique(n))

[54 30 77 89 77 34  3 89 43 82 52 63 24 94 99]
[ 3 24 30 34 43 52 54 63 77 82 89 94 99]


In [66]:
# 16. Given prices = np.array([199,450,89,999,320]), use np.clip() to cap all prices between 100 and 500.
prices = np.array([199,450,89,999,320])
print(np.clip(prices,100,500))

[199 450 100 500 320]
