NUMPY day 1

heading, can me be made with the help of markdown option

In [1]:
import numpy as np

In [1]:
print(25+3)

28


In [2]:
!pip install numpy


In [1]:
import time
import numpy as np
size=10000000
# list
a=list(range(size))

start_a=time.time()
a=list(map(lambda i: i**2,a))
end_a=time.time()-start_a

# array
a=np.arange(size)
start_b=time.time()
a=[a**2]
end_b=time.time()-start_b

print("time taken by list",end_a)
print("time taken by array",end_b)


time taken by list 1.631098985671997
time taken by array 0.020901203155517578


numpy day 2 => array

In [12]:
# how to create an array --------------> answer---> .array()

a = [12,23,34]
print(a)
print(type(a))

[12, 23, 34]
<class 'list'>


In [17]:
# array using list

arr=np.array([12,23,34])
print(arr)
print(type(arr)) #shows the class of array

[12 23 34]
<class 'numpy.ndarray'>


In [21]:
arr10=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr10)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# array attribute
#1 .ndim
# used to check the dimention of the array

In [24]:
print(arr10.ndim)

1


In [25]:
#2 .shape
# used to check the numbers of rows and columns

In [27]:
print(arr10.shape)

(10,)


In [28]:
#3 .size
# used to find the numbers of elements

In [30]:
print(arr10.size)

10


In [31]:
#4 .dtype
# used to check the datatype array is holding

In [4]:
arr1=np.array([12,34,56])
arr2=np.array([12.12,34.23,56.56])
arr3=np.array([1,1.25,"5",5.67])

print(arr1.dtype)
print(arr2.dtype)
print("'U' means unicode and the number next to it is the string length",arr3.dtype)
print(arr2.itemsize)

int64
float64
'U' means unicode and the number next to it is the string length <U32
8


In [42]:
#5 .itemsize
# used to check how much memory a single element of an array stores

In [49]:
print("size of integer element",arr1.itemsize)
print("size of float element",arr2.itemsize)
print("size of string element",arr3.itemsize)

size of integer element 8
size of float element 8
size of string element 128


TASK, print the btotal memory of an array

In [7]:
arr5=np.array([12,23,34,45,56])
print(arr5.size*arr5.itemsize)


40


homework task

In [52]:
#1 create an array containing element 1-15 
#2 create an array of mixed datatype containing 4 element and tell what data type will array change into and why
#3 on the above created array find the datatype of elements 
#4 create an array of size 7 and also print the size
#5 create an array of first five even numbers and
#    print size, datatype, total memory of array, shape of array, 
#    and the dimention of the array and also write one line defination of what the attribuetes are doing.

day15Sept how to make 2D array

In [11]:
arr=np.array([[1,2],[3,4],[5,6]])print(arr.shape)

(3, 2)


In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr)

(3, 3)
2
9
8
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [36]:
# 1D array usng function, 1 to 100

arr=np.array([np.arange(1,100)])
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
  73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
  97 98 99]]


In [42]:
# 1D array using finction, 1-50 with steps of 5
arr=np.array([np.arange(0,50,5)])
print(arr)

[[ 0  5 10 15 20 25 30 35 40 45]]


In [4]:
# 1D array of first 10 even numbers
arr=np.array(np.arange(2,10,2))
print(arr)

[2 4 6 8]


In [5]:
# creating 2D array using numpy arange()
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# .reshape
# used to reshape an array into a matrix 
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# create a matrix of 9x9 
arr=np.arange(1,82).reshape(9,9)
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [20]:
# .random
# prints float random values between 0-1
n=np.random.random(20)
print(n)
# it can also be reshaped
print(n.reshape(4,5))

[0.13204198 0.36418757 0.39647367 0.60245803 0.99171929 0.28000876
 0.60289756 0.75895876 0.44938371 0.4243661  0.23078593 0.42130153
 0.49653039 0.61655624 0.08852539 0.46083766 0.55360379 0.09096663
 0.01956097 0.48691919]
[[0.13204198 0.36418757 0.39647367 0.60245803 0.99171929]
 [0.28000876 0.60289756 0.75895876 0.44938371 0.4243661 ]
 [0.23078593 0.42130153 0.49653039 0.61655624 0.08852539]
 [0.46083766 0.55360379 0.09096663 0.01956097 0.48691919]]


In [23]:
# randint
# returns random integer(s) between two integers
# random.randint(from,to,how many numbers)
n=np.random.randint(12)
print(n)

5


In [24]:
# got 6 random integers and reshaped them into 2x3 matrix
n=np.random.randint(10,70,6).reshape(3,2)
print(n)

[[36 20]
 [49 60]
 [18 57]]


In [3]:
# create an array, of random integer numbers from 1 to 51 and reshape the array into the possible formats
n=np.random.randint(1,51,36)
print(n.reshape(6,6))

# print(n.reshape(2,18))
# print(n.reshape(18,2))
# print(n.reshape(9,4))
# print(n.reshape(4,9))
# print(n.reshape(12,3))
# print(n.reshape(3,12))
# print(n.reshape(1,36))
# print(n.reshape(36,1))

[[11 14  6  3 31 26]
 [45 34 47 44 20 43]
 [30 27 33 34  7 14]
 [21  3 23  2 28  3]
 [32 43 16 28 17 30]
 [39 16 35 42 27 45]]


In [51]:
# zeros
# returns desired amount of zeros as float datatype
a=np.zeros(4)
print(a)

# it allows us to make matrix without the use of .reshape
a=np.zeros([2,2])
print(a)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [55]:
# 5x5 matrix of zeros witht eh help of reshape and without using reshape
# using reshape
a=np.zeros(25).reshape(5,5)
print(a)
# wihtout the use oof reshape

a=np.zeros([5,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:
# ones
# returns desired amount of ones as float datatype
a=np.ones(4)
print(a)

# it allows us to make matrix without the use of .reshape
a=np.ones([2,2])
print(a)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [9]:
n=np.arange(1,13).reshape(2,6)
print(n.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
n=np.arange(0,21,2)
print(n.reshape(11,1))


[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]]


day17Sept

In [4]:
# .eye used to make awn identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#  how to convert float values into integer
a=np.eye(4,dtype=int)
print(a)
m=np.random.randint(3,13,(3,6))
print(m)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[11  3  8  5 10  9]
 [ 9  3  6  9  4  5]
 [11  3  9  8  6 10]]


In [7]:
# using indexing in a 2D array
print(m[1,2])

4


In [13]:
# boolean indexing
# applies condition on the indexxing and gives values which satisfies the condition
print(m[m%2==0])

[ 8 10  6  4  8  6 10]


In [12]:
d=np.zeros((4,4),dtype=int)

print(d)

d[0:1,:]=1
d[1:3,0:1]=1
d[1:3,3:]=1
d[3:,:]=1
print(d)

# easier approach

e=np.ones((4,4),dtype=int)
e[1:3,1:3]=0
print(e)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [69]:
b=np.ones(9).reshape(3,3)
print(b*5)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [13]:
b=np.ones(16).reshape(4,4)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


18Sept 

In [18]:
# linspace() --- linear space array, which means it creates an arrray where each elements will have same size diffrence
a=np.linspace(0,20,5)
print(a)

[ 0.  5. 10. 15. 20.]


In [31]:
b=np.random.randint(9,18,(3,3))
print(b)

[[12 16 16]
 [ 9 13 16]
 [15 14 10]]


In [35]:
# flatten --- used to convert any dimentiom of array into 1D array, a copy

flat=b.flatten()
print(flat)

[12 16 16  9 13 16 15 14 10]


In [36]:
# ravel --- used to convert any dimentiom of array into 1D array, a reference

ral=b.ravel()
print(ral)

[12 16 16  9 13 16 15 14 10]


In [38]:
# diffrence between flatten and ravel
# flatten creates a copy of the array, and changes made to it will not affect the original data
# ravel does not create a copy rather it only referes to the original data, and changes made to ravel will change the original data aswell

flat=b.flatten()
flat[1]=1234
print(flat)

ral=b.ravel()
ral[1]=1234
print(b)

[  12 1234   16    9   13   16   15   14   10]
[[  12 1234   16]
 [   9   13   16]
 [  15   14   10]]


In [51]:
# # 1D array
# arr0=np.array([1,2,3,4,5,55,6,7,8,9])
# for x in arr0:
#     print(x)

# # 2D array
# arr1=np.array([[1,2,3,4,5],[55,6,7,8,9]])
# for x in arr1:
#     for y in x:
#         print(y)
        
# this is hectic, so we use np.nditer(arrayName) to iterate any dimentional array without the use of multiple for loops
# .nditer
arr1=np.array([[1,2,3,4,5],[55,6,7,8,9]])
for i in np.nditer(arr1):
    print(i)


1
2
3
4
5
55
6
7
8
9


In [52]:
#broadcasting, is a process of performing any change on every element of an array using a condition

for i in np.nditer(arr1):
    print(i*2)

2
4
6
8
10
110
12
14
16
18


In [28]:
arr=np.random.randint(6,12,(2,3))
print(arr)

[[11  9  6]
 [ 9  6 11]]


In [30]:
arr=np.random.randint(1,10,(3,3))
print(arr-5)

[[-2  0  3]
 [ 0 -4 -4]
 [ 4  4  1]]


In [36]:
eyee=np.eye(5)
print(eyee*5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [12]:
a=np.zeros(9).reshape(3,3)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr=np.random.randint(0,101,100).reshape(10,10)
print(arr)
min=0
max=0
for i in np.nditer(arr):
    if i>=max:
        max=i
    elif i<=min:
        min=i
print(f"max value in the matrix {max}")
print(f"min value in the matrix {min}")

[[96 45 18  8 50  5  4 61 25 48]
 [67 81 71 39 75 42 89 50 18 38]
 [26 35 14 19 71 35 18 16 31 81]
 [64 97 52 63 52 45 61 15 39  1]
 [50 57 50 91 55 77 67 24  0 73]
 [89  0 64 93 21 21 85 88 62  9]
 [66 98 84 98 12 43 43 87 94 52]
 [41 22  8  4 64 50  2 91  2 97]
 [33 35 69 32 97 35 46 65 77 54]
 [ 1  1 63  9 19 61 67 91 71 43]]
max value in the matrix 98
min value in the matrix 0


In [4]:
# np.where
# it returns the indexing of elements which satisfy the condition

arr=np.array([12,34,543,12,65,23])
print(arr)
print(np.where(arr>50))



[ 12  34 543  12  65  23]
(array([2, 4]),)


In [7]:
# syntax:- np.where(condition,true,false)
print(np.where(arr>50,"pass","fail"))

['fail' 'fail' 'pass' 'fail' 'pass' 'fail']


In [9]:
# np.full 
# used to create an matrix of a single element

print(np.full((3,4),17))

[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


In [5]:
# arithmetic operations on 1D matrix
# + - / *
a=np.array([1,2,4,5,6])
b=np.array([4,2,5,8,2])

print(a+b)
print(a-b)
print(a/b)
print(a*b)


[ 5  4  9 13  8]
[-3  0 -1 -3  4]
[0.25  1.    0.8   0.625 3.   ]
[ 4  4 20 40 12]


In [16]:
# arithmetic operations on 2D matrix

c=np.array([[1,2],[4,2]])
d=np.array([[4,2],[1,2]])

print(c)
print()
print(d)
print()

print(c+d)
print(c-d)
print(c/d)
print(c*d) #it does not give the real matrix multiplication
print(c@d) # @, np.dot(a,b) and np.matmul(a,b) are used to do matrix multiplication

[[1 2]
 [4 2]]

[[4 2]
 [1 2]]

[[5 4]
 [5 4]]
[[-3  0]
 [ 3  0]]
[[0.25 1.  ]
 [4.   1.  ]]
[[4 4]
 [4 4]]
[[ 6  6]
 [18 12]]


In [25]:
# stacking, merge, concatinate
e=np.array([[1,2],[4,2]])
f=np.array([[4,2],[1,2]])
print(e)
print()
print(f)
print()


[[1 2]
 [4 2]]

[[4 2]
 [1 2]]



In [26]:
# horizontal stacking
print(np.hstack((e,f)))

[[1 2 4 2]
 [4 2 1 2]]


In [27]:
# vertical stacking
print(np.vstack((e,f)))

[[1 2]
 [4 2]
 [4 2]
 [1 2]]


In [106]:
# 3x3 random array and one with 0 to 1
g=np.random.randint(0,101,9).reshape(3,3)
print(g)
h=np.random.random(9).reshape(3,3)
print(h)
print()
print(np.hstack((g,h)))
print()
print(np.vstack((g,h)))

[[91  7 26]
 [25  9 61]
 [67  9 83]]
[[0.0323358  0.59695066 0.97652138]
 [0.3444963  0.43608379 0.53029727]
 [0.39651788 0.90642893 0.01318571]]

[[9.10000000e+01 7.00000000e+00 2.60000000e+01 3.23357951e-02
  5.96950664e-01 9.76521378e-01]
 [2.50000000e+01 9.00000000e+00 6.10000000e+01 3.44496296e-01
  4.36083791e-01 5.30297271e-01]
 [6.70000000e+01 9.00000000e+00 8.30000000e+01 3.96517878e-01
  9.06428930e-01 1.31857144e-02]]

[[9.10000000e+01 7.00000000e+00 2.60000000e+01]
 [2.50000000e+01 9.00000000e+00 6.10000000e+01]
 [6.70000000e+01 9.00000000e+00 8.30000000e+01]
 [3.23357951e-02 5.96950664e-01 9.76521378e-01]
 [3.44496296e-01 4.36083791e-01 5.30297271e-01]
 [3.96517878e-01 9.06428930e-01 1.31857144e-02]]


In [31]:
# hw
z=np.linspace(0,200,16).reshape(4,4)
print(z)

[[  0.          13.33333333  26.66666667  40.        ]
 [ 53.33333333  66.66666667  80.          93.33333333]
 [106.66666667 120.         133.33333333 146.66666667]
 [160.         173.33333333 186.66666667 200.        ]]


In [29]:
# hw
r = np.random.randint(0, 10, size=(4,5))
print(r)

[[7 7 9 9 9]
 [1 7 1 8 5]
 [2 5 8 0 0]
 [5 9 9 0 7]]


In [60]:
# hw
ones=np.ones(25).reshape(5,5)
print(ones)
print()
ones[:2,1:4]=3
ones[:3,4:]=7
ones[2:3,1:4]=8
ones[4:,:4]=9
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 3. 3. 3. 7.]
 [1. 3. 3. 3. 7.]
 [1. 8. 8. 8. 7.]
 [1. 1. 1. 1. 1.]
 [9. 9. 9. 9. 1.]]


In [65]:
# hw
n=np.linspace(50,200,10,dtype=int)
print(n)
print(np.where(n%2==0,-1,0))

[ 50  66  83 100 116 133 150 166 183 200]
[-1 -1  0 -1 -1  0 -1 -1  0 -1]


In [71]:
# hw
a=np.array([[12,21],[34,43]])
b=np.array([[34,43],[12,21]])
print(a+b)
print(a-b)
print(a@b)
print(np.dot(a,b))
print(np.matmul(a,b))

[[46 64]
 [46 64]]
[[-22 -22]
 [ 22  22]]
[[ 660  957]
 [1672 2365]]
[[ 660  957]
 [1672 2365]]
[[ 660  957]
 [1672 2365]]
