NUMPY day 1

heading, can me be made with the help of markdown option

In [1]:
import numpy as np

In [1]:
print(25+3)

28


In [2]:
!pip install numpy


In [1]:
import time
import numpy as np
size=10000000
# list
a=list(range(size))

start_a=time.time()
a=list(map(lambda i: i**2,a))
end_a=time.time()-start_a

# array
a=np.arange(size)
start_b=time.time()
a=[a**2]
end_b=time.time()-start_b

print("time taken by list",end_a)
print("time taken by array",end_b)


time taken by list 1.631098985671997
time taken by array 0.020901203155517578


numpy day 2 => array

In [12]:
# how to create an array --------------> answer---> .array()

a = [12,23,34]
print(a)
print(type(a))

[12, 23, 34]
<class 'list'>


In [17]:
# array using list

arr=np.array([12,23,34])
print(arr)
print(type(arr)) #shows the class of array

[12 23 34]
<class 'numpy.ndarray'>


In [21]:
arr10=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr10)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# array attribute
#1 .ndim
# used to check the dimention of the array

In [24]:
print(arr10.ndim)

1


In [25]:
#2 .shape
# used to check the numbers of rows and columns

In [27]:
print(arr10.shape)

(10,)


In [28]:
#3 .size
# used to find the numbers of elements

In [30]:
print(arr10.size)

10


In [31]:
#4 .dtype
# used to check the datatype array is holding

In [4]:
arr1=np.array([12,34,56])
arr2=np.array([12.12,34.23,56.56])
arr3=np.array([1,1.25,"5",5.67])

print(arr1.dtype)
print(arr2.dtype)
print("'U' means unicode and the number next to it is the string length",arr3.dtype)
print(arr2.itemsize)

int64
float64
'U' means unicode and the number next to it is the string length <U32
8


In [42]:
#5 .itemsize
# used to check how much memory a single element of an array stores

In [49]:
print("size of integer element",arr1.itemsize)
print("size of float element",arr2.itemsize)
print("size of string element",arr3.itemsize)

size of integer element 8
size of float element 8
size of string element 128


TASK, print the btotal memory of an array

In [7]:
arr5=np.array([12,23,34,45,56])
print(arr5.size*arr5.itemsize)


40


homework task

In [52]:
#1 create an array containing element 1-15 
#2 create an array of mixed datatype containing 4 element and tell what data type will array change into and why
#3 on the above created array find the datatype of elements 
#4 create an array of size 7 and also print the size
#5 create an array of first five even numbers and
#    print size, datatype, total memory of array, shape of array, 
#    and the dimention of the array and also write one line defination of what the attribuetes are doing.

day15Sept how to make 2D array

In [11]:
arr=np.array([[1,2],[3,4],[5,6]])print(arr.shape)

(3, 2)


In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr)

(3, 3)
2
9
8
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [36]:
# 1D array usng function, 1 to 100

arr=np.array([np.arange(1,100)])
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
  73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
  97 98 99]]


In [42]:
# 1D array using finction, 1-50 with steps of 5
arr=np.array([np.arange(0,50,5)])
print(arr)

[[ 0  5 10 15 20 25 30 35 40 45]]


In [48]:
# 1D array of first 10 even numbers
arr=np.array(np.arange(2,10,2))
print(arr)

[2 4 6 8]


In [4]:
# creating 2D array using numpy arange()
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [7]:
# .reshape
# used to reshape an array into a matrix 
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# create a matrix of 9x9 
arr=np.arange(1,82).reshape(9,9)
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [20]:
# .random
# prints float random values between 0-1
n=np.random.random(20)
print(n)
# it can also be reshaped
print(n.reshape(4,5))

[0.13204198 0.36418757 0.39647367 0.60245803 0.99171929 0.28000876
 0.60289756 0.75895876 0.44938371 0.4243661  0.23078593 0.42130153
 0.49653039 0.61655624 0.08852539 0.46083766 0.55360379 0.09096663
 0.01956097 0.48691919]
[[0.13204198 0.36418757 0.39647367 0.60245803 0.99171929]
 [0.28000876 0.60289756 0.75895876 0.44938371 0.4243661 ]
 [0.23078593 0.42130153 0.49653039 0.61655624 0.08852539]
 [0.46083766 0.55360379 0.09096663 0.01956097 0.48691919]]


In [23]:
# randint
# returns random integer(s) between two integers
# random.randint(from,to,how many numbers)
n=np.random.randint(12)
print(n)

5


In [24]:
# got 6 random integers and reshaped them into 2x3 matrix
n=np.random.randint(10,70,6).reshape(3,2)
print(n)

[[36 20]
 [49 60]
 [18 57]]


In [46]:
# create an array, of random integer numbers from 1 to 51 and reshape the array into the possible formats
n=np.random.randint(1,51,36)
print(n.reshape(6,6))

print(n.reshape(2,18))
print(n.reshape(18,2))
print(n.reshape(9,4))
print(n.reshape(4,9))
print(n.reshape(12,3))
print(n.reshape(3,12))
print(n.reshape(1,36))
print(n.reshape(36,1))

[[47 34 38 21 21 32]
 [12 48 13 49 17 49]
 [ 4 26 37 26 28 20]
 [14 23 42 48 37 41]
 [38 36 25 41  9 39]
 [39 50  8 33 26 26]] /n/n
[[47 34 38 21 21 32 12 48 13 49 17 49  4 26 37 26 28 20]
 [14 23 42 48 37 41 38 36 25 41  9 39 39 50  8 33 26 26]]
[[47 34]
 [38 21]
 [21 32]
 [12 48]
 [13 49]
 [17 49]
 [ 4 26]
 [37 26]
 [28 20]
 [14 23]
 [42 48]
 [37 41]
 [38 36]
 [25 41]
 [ 9 39]
 [39 50]
 [ 8 33]
 [26 26]]
[[47 34 38 21]
 [21 32 12 48]
 [13 49 17 49]
 [ 4 26 37 26]
 [28 20 14 23]
 [42 48 37 41]
 [38 36 25 41]
 [ 9 39 39 50]
 [ 8 33 26 26]]
[[47 34 38 21 21 32 12 48 13]
 [49 17 49  4 26 37 26 28 20]
 [14 23 42 48 37 41 38 36 25]
 [41  9 39 39 50  8 33 26 26]]
[[47 34 38]
 [21 21 32]
 [12 48 13]
 [49 17 49]
 [ 4 26 37]
 [26 28 20]
 [14 23 42]
 [48 37 41]
 [38 36 25]
 [41  9 39]
 [39 50  8]
 [33 26 26]]
[[47 34 38 21 21 32 12 48 13 49 17 49]
 [ 4 26 37 26 28 20 14 23 42 48 37 41]
 [38 36 25 41  9 39 39 50  8 33 26 26]]
[[47 34 38 21 21 32 12 48 13 49 17 49  4 26 37 26 28 20 14 23 42 48 37

In [51]:
# zeros
# returns desired amount of zeros as float datatype
a=np.zeros(4)
print(a)

# it allows us to make matrix without the use of .reshape
a=np.zeros([2,2])
print(a)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [55]:
# 5x5 matrix of zeros witht eh help of reshape and without using reshape
# using reshape
a=np.zeros(25).reshape(5,5)
print(a)
# wihtout the use oof reshape

a=np.zeros([5,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:
# ones
# returns desired amount of ones as float datatype
a=np.ones(4)
print(a)

# it allows us to make matrix without the use of .reshape
a=np.ones([2,2])
print(a)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
